<?php include 'app/views/includes/header.phtml'?>
<script src="http://ajax.microsoft.com/ajax/jquery.validate/1.7/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/additional-methods.js"></script>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-login">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <a href="#" class="active" id="login-form-link">Write Exam</a>
                        </div>
                        <div class="col-xs-6">
                            <a href="#" id="register-form-link">Set Exam</a>
                        </div>
                    </div>
                    <hr>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <form id="login-form" action="/entry" method="post" role="form" style="display: block;">
                                <input type="hidden" value="login" name="action">
                                <div class="form-group">
                                    <input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
                                </div>
                                <div class="form-group">
                                    <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
                                </div>
                                <div class="form-group text-center">
                                    <input type="checkbox" tabindex="3" class="" name="remember" id="remember">
                                    <label for="remember"> Remember Me</label>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="write exam">
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <form id="register-form" action="/entry" method="post" role="form" style="display: none;" enctype="multipart/form-data">
                                <input type="hidden" value="register" name="action">
                                <div class="form-group">
                                    <input type="text" name="course" id="course" tabindex="1" class="form-control" placeholder="Course code" value="">
                                </div>
                                <div class="form-group">
                                    <input type="email" name="email" id="email" tabindex="1" class="form-control" placeholder="Email Address" value="">
                                </div>
                                <div class="form-group">
                                    <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Auth key">
                                </div>
                                <div class="form-group">
                                    <input type="text" name="time" id="time" tabindex="2" class="form-control" placeholder="Time">
                                </div>
                                <span class="control-fileupload">
                                      <label for="file">Choose a file :</label>
                                      <input type="file" name="file" id="file">
                                </span>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Register Now">
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function() {

        $('#login-form-link').click(function(e) {
            $("#login-form").delay(100).fadeIn(100);
            $("#register-form").fadeOut(100);
            $('#register-form-link').removeClass('active');
            $(this).addClass('active');
            e.preventDefault();
        });
        $('#register-form-link').click(function(e) {
            $("#register-form").delay(100).fadeIn(100);
            $("#login-form").fadeOut(100);
            $('#login-form-link').removeClass('active');
            $(this).addClass('active');
            e.preventDefault();
        });
        $('#file').change(function(){
            var t = $(this).val();
            var labelText = 'File : ' + t.substr(12, t.length);
            $(this).prev('label').text(labelText);
        });
        $('form[id="register-form"]').validate({
            rules: {
                course: 'required',
                time: 'required',
                email: {
                    required: true,
                    email: true,
                },
                password: {
                    required: true,
                    minlength: 8,
                },
                file: {
                    required: true,
                    extension: "csv"
                }
            },
            messages: {
                course: 'This field is required',
                time: 'This field is required',
                email: 'Enter a valid email',
                password: {
                    minlength: 'Password must be at least 8 characters long'
                }
            },
            submitHandler: function(form) {
                form.submit();
            }
        });
        $('form[id="login-form"]').validate({
            rules: {
                username: 'required',
                password: {
                    required: true,

                },
            },
            messages: {
                username: 'This field is required',
                password: 'This field is required',
            },
            submitHandler: function(form) {
                form.submit();
            }
        });
    });
</script>