<?php include 'app/views/includes/header.phtml'?>
<script src="https://printjs-4de6.kxcdn.com/print.min.js"></script>
<button class="btn btn-danger" onclick="end(<?php echo $this->course ?>)">Stop</button>
<div class="space"><br></div>
<table id="result">
    <tr>
        <th>Reg. No</th>
        <th>Score</th>
        <th>Time</th>
    </tr>
    <?php


    foreach ($this->result as $result) {
        echo '<tr>';
        echo '<td>' . $result['stu_id'] . '</td>';
        echo '<td>' . $result['score']. '</td>';


        ?>
        <td>
            <?php if ($result['time'] == -1)echo 'done';
            else echo $result['time'] ; ?>
        </td>
        <?php
        echo '</tr>';
    }

    ?>
</table>
<script>
    function end(course)
    {
        if (confirm("are you sure you want to end the exam")){
            clearInterval(inter);
        let xhttp = new XMLHttpRequest();

            css='table {width:98%; text-align:left; border:1px solid #DDDDDD; font-size:12px; color:#000;background:#fff; margin-bottom:10px;} table th {background-color:#E5E5E5; border:1px solid #BBBBBB; padding:3px 6px; font-weight:normal; color:#000;}table tr td {border:1px solid #DDDDDD; padding:5px 6px;}';


        xhttp.open('DELETE','/watch/'+course);
        xhttp.onload = function ()
        {
            close();
            printJS({
                printable: 'result',
                type: 'html',
                style: css});
        };
        xhttp.send();
        }

    }
    function close(){
        window.location.href= 'http://www.ans.com';
    }
    var inter= setInterval(function() {
        window.location.reload();
    }, 6000);
</script>