<?php include 'app/views/includes/header.phtml'?>
<button class="btn btn-danger" onclick="end(<?php echo $this->course ?>)">Stop</button>
<div class="space"><br></div>
<table>
    <tr>
        <th>Reg. No</th>
        <th>Score</th>
        <th>Time</th>
    </tr>
    <?php


    foreach ($this->result as $result) {
        echo '<tr>';
        echo '<td>' . $result['stu_id'] . '</td>';
        echo '<td>' . $result['score']. '</td>';


        ?>
        <td>
            <?php echo $result['time']; ?>
        </td>
        <?php
        echo '</tr>';
    }

    ?>
</table>
<script>
    function end(course)
    {
        if (confirm("are you sure you want to end the exam")){
        let xhttp = new XMLHttpRequest();

        xhttp.open('DELETE','/watch/'+course);

        xhttp.send();
        }
    }
</script>