<?php include 'app/views/includes/header.phtml'?>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div>
                <img src="/app/public/img/avate.jpg" height="150" width="150">
            </div>
            <h4>
                Show us what you got <?php $this->result['id']; ?>
            </h4>
            <div>
                <div id="del-countdown">
                    <div id="units">
                        <span>Hours</span>
                        <span>Minutes</span>
                        <span>Seconds</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div>
                <?php  print
                print_r($this->result);
                ?>
            </div>
            <div class="space">
                <?php echo $this->result['question'] ?>
            </div>
            <div>
                <form>
                    <div class="row">
                        <div class="radio col-md-6">
                            <label><input type="radio" name="answer" checked>Option 1</label>
                        </div>
                        <div class="radio col-md-6">
                            <label><input type="radio" name="answer">Option 2</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="radio col-md-6">
                            <label><input type="radio" name="answer" >Option 3</label>
                        </div>
                        <div class="radio col-md-6">
                            <label><input type="radio" name="answer" >Option 3</label>
                        </div>
                    </div>
                </form>
            </div>
            <div class="space">
                <div class="col-md-6">
                    <button>next ></button>
                </div>
                <div class="col-md-6">
                    <button onclick="getAnswered()">previous <</button>
                </div>
            </div>
            <div class="space" id="quesNo">
            </div>
        </div>
    </div>
</div>
<script>
    function getAnswered()
    {
        let xhttp;
        xhttp = new XMLHttpRequest();
        var data = JSON.stringify({
            action:"answered"
        });
        xhttp.open("POST","/write");
        xhttp.setRequestHeader('Content-type', 'application/json');
        xhttp.responseType = 'json';
        xhttp.onload = function () {
            let response = xhttp.response;
            response.forEach(element => {
                result=document.getElementById('quesNo');
                if(response.s_ans == null)
                    result.innerHTML += '<button>'+element.id+'</button>';
                else
                    result.innerHTML += '<button class="active">'+element.id+'</button>';
            });
            console.log(response[1]);
        };
        xhttp.send(data);
    }
</script>