<?php include 'app/views/includes/header.phtml'?>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div>
                <img src="/app/public/img/avate.jpg" height="150" width="150">
            </div>
            <h4>
                Show us what you got <br><?php echo $this->result; ?>
            </h4>
            <div>
                <div id="del-countdown">
                    <div id="units">

                    </div>
                </div>
                <div>
                    <button class="btn btn-success" onclick="submit()">submit</button>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="space" id="question">
            </div>
            <div>
                <form>
                    <div class="row" id="answers">

                    </div>
                </form>
            </div>
            <div class="space">
                <input name="questionNo" type="text" id="NO" hidden>
                <input name="o" type="text" id="totalQ" hidden>
                <div class="col-md-6">
                    <button onclick="getNext(document.getElementById('NO').value-1 ===0 ? 1 : parseInt(document.getElementById('NO').value)-1)">previous <</button>
                </div>
                <div class="col-md-6">
                    <button onclick="getNext(document.getElementById('NO').value === document.getElementById('totalQ').value ? document.getElementById('NO').value : parseInt(document.getElementById('NO').value) +1 )">next ></button>
                </div>
            </div>
            <div class="space"><hr></div>
            <div class="space" id="quesNo">
            </div>
        </div>
    </div>
</div>
<script>
    window.onload = function () {
        getAnswered();
        getNext(1);
        getTime();
    };
    function getAnswered()
    {
        let xhttp;
        xhttp = new XMLHttpRequest();
        var data = JSON.stringify({
            action:"answered"
        });
        xhttp.open("POST","/write");
        xhttp.setRequestHeader('Content-type', 'application/json');
        xhttp.responseType = 'json';
        result=document.getElementById('quesNo');
        result.innerHTML='';
        xhttp.onload = function () {
            let response = xhttp.response;

            rows=response.length;
            response.forEach(element => {

                if(element.s_ans !== null)
                    result.innerHTML += '<button onclick="getNext('+element.id+')" class="active">'+element.id+'</button>';
                else
                    result.innerHTML += '<button onclick="getNext('+element.id+');getAnswered()">'+element.id+'</button>';
            });
            document.getElementById('totalQ').value = rows;
        };
        xhttp.send(data);
    }
    function getNext(id)
    {
        let xhtp = new XMLHttpRequest();
        var data = JSON.stringify({
            action:"getQuestion",
            question: id
        });
        xhtp.open('POST','/write');
        xhtp.setRequestHeader('Content-type', 'application/json');
        xhtp.responseType = 'json';
        xhtp.onload = function () {
            let response = xhtp.response;

            //remove answer to the question
            delete response.ans;

            document.getElementById('question').innerHTML=response.question;

            //remove the question from the object
            delete response.question;

            //convert the remaining part of object to array
            const answers = Object.keys(response).map(i => response[i]);

            answer=document.getElementById('answers');

            answer.innerHTML='';
            for (let i =0; i<answers.length-1; i++) {

                answer.innerHTML +='<div class="radio">';
                if (answers[i] === answers[answers.length-1]){
                    answer.innerHTML +='<label><input type="radio" name="answer" value="'+answers[i]+'"  checked onclick="answerQuestion('+id+')">'+answers[i]+'</label>';
                }
                else{
                    answer.innerHTML +='<label><input type="radio" name="answer" value="'+answers[i]+'" onclick="answerQuestion('+id+')">'+ answers[i] +'</label>';
                }
                answer.innerHTML +='</div>';
            }

            document.getElementById('NO').value = id;

            //console.log(response);
        };
        xhtp.send(data);
    }
    function answerQuestion(id) {
        let xhttp;
        xhttp = new XMLHttpRequest();
        let radios = document.getElementsByName('answer');

        let s_ans;
        for (var i = 0, length = radios.length; i < length; i++)
        {
            if (radios[i].checked)
            {
                s_ans = radios[i].value;
                console.log(s_ans);
            }
        }

        var data = JSON.stringify({
            action:"answerQ",
            answer:s_ans,
            question: id
        });
        xhttp.open("POST","/write");
        xhttp.setRequestHeader('Content-type', 'application/json');
        //xhttp.responseType = 'json';
        xhttp.onload = function () {
            let response = xhttp.response;
            getAnswered();

        };
        xhttp.send(data);

        checkAnswer();
    }
    function checkAnswer()
    {
        let xhttp;
        xhttp = new XMLHttpRequest();

        var data = JSON.stringify({
            action:"getScore",
            course:"<?php echo $this->course ?>"

        });
        xhttp.open("POST","/write");
        xhttp.setRequestHeader('Content-type', 'application/json');
        //xhttp.responseType = 'json';
        xhttp.onload = function () {

        };
        xhttp.send(data);
    }
    function getTime()
    {
        let xhttp;
        xhttp = new XMLHttpRequest();

        var data = JSON.stringify({
            action:"getTime",
            course:"<?php echo $this->course ?>"

        });
        xhttp.open("POST","/write");
        xhttp.setRequestHeader('Content-type', 'application/json');
        xhttp.responseType = 'json';
        xhttp.onload = function () {
            console.log(xhttp.response);
            if (xhttp.response === -1){
                alert('You are done with exams');
                window.location.href = 'http://www.ans.com';
            } else
                startTimer(xhttp.response)
        };
        xhttp.send(data);
    }
    function startTimer(duration) {
        var timer = duration*60, minutes, seconds;

        setInterval(function () {
            minutes = parseInt(timer / 60,10);
            seconds = parseInt(timer % 60,10);
            console.log(minutes);
            minutes = minutes < 10 ? "0" + minutes : minutes;
            seconds = seconds < 10 ? "0" + seconds : seconds;

            document.getElementById('del-countdown').textContent = minutes + ":" + seconds;

            if (--timer < 0) {
                timer = duration;
            }
        }, 1000);
        //update db on the time
        window.updateTime =setInterval(function () {
            let xhttp;
            xhttp = new XMLHttpRequest();

            var data = JSON.stringify({
                action:"saveTime",
                time:minutes,
                course:"<?php echo $this->course ?>"

            });
            xhttp.open("POST","/write");
            xhttp.setRequestHeader('Content-type', 'application/json');
            xhttp.responseType = 'json';
            xhttp.onload = function () {
            };
            xhttp.send(data);
        },60000)
    }
    function submit(){
        clearInterval(updateTime)
        let xhttp;
        xhttp = new XMLHttpRequest();

        var data = JSON.stringify({
            action:"submit",
            time:-1,
            course:"<?php echo $this->course ?>"
        });
        xhttp.open("POST","/write");
        xhttp.setRequestHeader('Content-type', 'application/json');
        xhttp.responseType = 'json';
        xhttp.onload = function () {
            window.location.href = 'http://www.ans.com';
        };
        xhttp.send(data);
    }

</script>